/* Shared business rules. The server always authenticates the actor independently. */
export const SERVICES = ['Social', 'Mini Date', 'Night Out'];
export const ID_STATES = ['Not Started','Pending','Action Required','Manual Review','Verified','Rejected','Suspended'];
export const PROFILE_STATES = ['Draft','Pending Verification','Action Required','Verified—Profile Incomplete','Pending Admin Approval','Changes Required','Approved','Rejected','Suspended'];
export const MULTIPLIER = 2.5;
export const POLICY_VERSION = 'HL-2.5-v1';
export class RuleError extends Error { constructor(message,status=400){super(message);this.status=status} }
const must=(condition,message,status=400)=>{if(!condition)throw new RuleError(message,status)};
const copy=value=>structuredClone(value);
export const id=()=>globalThis.crypto.randomUUID();
export const now=()=>new Date().toISOString();
export function age(dob,at=new Date()) { const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(at); const n=k=>Number(parts.find(x=>x.type===k).value); const [y,m,d]=String(dob).split('-').map(Number); return n('year')-y-Number(n('month')<m||(n('month')===m&&n('day')<d)); }
export function validDOB(dob,min,at=new Date()){return /^\d{4}-\d{2}-\d{2}$/.test(String(dob))&&Number.isFinite(Date.parse(dob))&&new Date(dob).toISOString().slice(0,10)===dob&&age(dob,at)>=min&&age(dob,at)<=120}
export const minimumAge=role=>role==='customer'?25:18;
export function price(basePaise){must(Number.isSafeInteger(basePaise)&&basePaise>=100&&basePaise<=10000000&&basePaise%2===0,'Enter a base price from ₹1 to ₹1,00,000 in whole paise (even paise).');return basePaise*5/2}
const text=(v,max=200)=>{must(typeof v==='string'&&v.trim().length<=max,'Invalid text.');return v.trim()};
export function identityEligible(u){return u?.status==='active'&&u.identity?.status==='Verified'&&validDOB(u.identity.verifiedDOB,minimumAge(u.role))}
export function membershipState(u){if(!identityEligible(u))return u?.status==='suspended'?'Suspended':'Not Eligible';if(!u.membership)return 'Payment Required';if(u.membership.status==='Active'&&Date.parse(u.membership.expiresAt)<=Date.now())return 'Expired';return u.membership.status}
export const customerEligible=u=>u?.role==='customer'&&identityEligible(u)&&membershipState(u)==='Active';
export const companionVisible=u=>u?.role==='companion'&&identityEligible(u)&&u.profileStatus==='Approved'&&!!u.published;
function getUser(s,userId){const u=s.users.find(x=>x.id===userId);must(u&&u.status!=='deleted','Account unavailable.',404);return u}
const notice=(s,user,title,body,reference='')=>{if(s.users.find(u=>u.id===user)?.notificationsEnabled===false&&['New message','Video introduction request','Voice call request'].includes(title))return;s.notifications.unshift({id:id(),user,title,body,reference,read:false,at:now()})};
const record=(s,actor,action,target,reason='')=>s.audit.push({id:id(),actor:actor.id,action,target,reason,at:now()});
const personName=u=>u.role==='companion'?(u.published?.nickname||u.lastPublished?.nickname||'Companion'):u.nickname;
const admin=(u)=>must(u.role==='admin'&&u.status==='active','Administrator access required.',403);
const member=(u)=>must(u.role!=='admin'&&u.status==='active','Account access is restricted.',403);
function pairEligible(s,c,t){must(customerEligible(c)&&companionVisible(t),'Verified identity, active customer membership, and approved companion profile are required.',403);must(!s.blocks.some(b=>(b.by===c.id&&b.target===t.id)||(b.by===t.id&&b.target===c.id)),'This connection is unavailable.',403)}
function interactionEligible(s,c){const customer=getUser(s,c.customer),companion=getUser(s,c.companion);must(customerEligible(customer)&&identityEligible(companion)&&!['Rejected','Suspended'].includes(companion.profileStatus),'Identity and active membership are required for communication.',403);must(!s.blocks.some(b=>(b.by===customer.id&&b.target===companion.id)||(b.by===companion.id&&b.target===customer.id)),'This connection is unavailable.',403)}
function connection(s,actor,ref){const c=s.connections.find(x=>x.id===ref);must(c&&(c.customer===actor.id||c.companion===actor.id),'Connection not found.',404);return c}
function booking(s,actor,ref){const b=s.bookings.find(x=>x.id===ref);must(b&&(actor.role==='admin'||[b.customer,b.companion].includes(actor.id)),'Booking not found.',404);return b}
const conflicts=(s,companion,start,hours,exclude='')=>s.bookings.some(b=>b.id!==exclude&&b.companion===companion&&(['Confirmed','In Progress'].includes(b.status)||(b.status==='Payment Pending'&&Date.parse(b.holdUntil)>Date.now()))&&Date.parse(b.start)<Date.parse(start)+hours*3600000&&Date.parse(b.start)+b.hours*3600000>Date.parse(start));
export function isAvailable(s,t,service,start,hours,exclude=''){
  const p=t.draft,rule=p.services.find(x=>x.name===service),date=new Date(start);if(!rule||!Number.isFinite(+date)||+date<=Date.now()||!rule.rates.some(x=>x.hours===hours)||Date.parse(p.pausedUntil||0)>Date.now())return false;
  const local=new Date(+date+19800000),minutes=local.getUTCHours()*60+local.getUTCMinutes(),mins=v=>Number(v.split(':')[0])*60+Number(v.split(':')[1]),begin=mins(rule.from),finish=mins(rule.to),overnight=finish<begin,previous=overnight&&minutes<finish,anchor=new Date(+local-(previous?86400000:0)),day=anchor.getUTCDay(),dateKey=anchor.toISOString().slice(0,10),startMinute=minutes+(previous?1440:0),endMinute=finish+(overnight?1440:0),endDate=new Date(+date+(hours*3600000-1)+19800000).toISOString().slice(0,10);
  return rule.days.includes(day)&&!rule.unavailable.includes(dateKey)&&!rule.unavailable.includes(local.toISOString().slice(0,10))&&!rule.unavailable.includes(endDate)&&startMinute>=begin&&startMinute+hours*60<=endMinute&&!conflicts(s,t.id,start,hours,exclude);
}
export function slots(s,t,service,hours){const values=[];for(let day=0;day<21;day++){const date=new Date(Date.now()+day*86400000+19800000).toISOString().slice(0,10);for(let hour=0;hour<24;hour++){const start=new Date(`${date}T${String(hour).padStart(2,'0')}:00:00+05:30`).toISOString();if(isAvailable(s,t,service,start,hours))values.push(start)}}return values.slice(0,60)}
function quote(t,service,hours){const rate=t.draft.services.find(x=>x.name===service)?.rates.find(x=>x.hours===hours);must(rate,'This service and duration are unavailable.');return {service,hours,basePaise:rate.basePaise,customerPaise:price(rate.basePaise),currency:'INR',policy:POLICY_VERSION,multiplier:MULTIPLIER,taxPaise:0,feePaise:0}}
export function profileChecklist(u){return [ ['Identity verified · 18+',identityEligible(u)],['Display name and city',!!u.draft.nickname&&!!u.city],['Introduction and languages',!!u.draft.bio&&u.draft.languages.length>0],['At least one profile photo',u.draft.photos.some(p=>p.status!=='Rejected')],['Services, prices and availability',u.draft.services.length>0&&u.draft.services.every(x=>x.rates.length&&x.days.length)],['Companion Guidelines accepted',!!u.guidelinesAt] ];}
export function publicProfile(u,s){const p=u.published;return {id:u.id,role:'companion',nickname:p.nickname,age:age(u.identity.verifiedDOB),city:u.city,gender:u.gender,bio:p.bio,hobbies:p.hobbies,languages:p.languages,details:p.details,photos:p.photos.filter(x=>x.status==='Approved').map(x=>({id:x.id,image:x.image})),videoEnabled:p.videoEnabled,services:u.draft.services.map(x=>({name:x.name,area:x.area,rates:x.rates.map(r=>({hours:r.hours,customerPaise:price(r.basePaise),currency:'INR'})),availability:x.rates.map(r=>({hours:r.hours,slots:slots(s,u,x.name,r.hours)}))})),ratings:s.ratings.filter(x=>x.about===u.id).map(x=>({value:x.value,at:x.at})),paused:Date.parse(u.draft.pausedUntil||0)>Date.now()};}
function planSnapshot(s){return copy(s.settings.membership)}
export function clientResult(s,userId,result){const r=copy(result);if(s.users.find(u=>u.id===userId)?.role==='customer'){const strip=v=>{if(v&&typeof v==='object'){delete v.basePaise;for(const child of Object.values(v))strip(child)}};strip(r)}return r}
export function view(s,userId){const u=getUser(s,userId),self=copy(u);delete self.passwordHash;
  self.membershipState=membershipState(u);self.verifiedAge=u.identity.status==='Verified'?age(u.identity.verifiedDOB):null;
  if(u.role==='admin')return {self,users:s.users.map(x=>{const v=copy(x);delete v.passwordHash;return v}),settings:copy(s.settings),connections:copy(s.connections),bookings:copy(s.bookings),orders:copy(s.orders),extensions:copy(s.extensions),notifications:s.notifications.filter(n=>n.user===u.id),tickets:copy(s.tickets),audit:copy(s.audit),calls:copy(s.calls),profiles:[],messages:[]};
  const visibleRecord=record=>clientResult(s,u.id,record);
  const own=c=>[c.customer,c.companion].includes(u.id),connections=s.connections.filter(own),bookings=s.bookings.filter(own),threads=connections.filter(c=>c.status==='Accepted').map(c=>c.id),peers=[...new Set([...connections,...bookings].map(c=>c.customer===u.id?c.companion:c.customer))].map(ref=>s.users.find(u=>u.id===ref)||{id:ref,role:'customer',nickname:'Deleted account',city:''});
  return {self,settings:{membership:planSnapshot(s),pricingPolicy:POLICY_VERSION},profiles:customerEligible(u)?s.users.filter(companionVisible).filter(t=>!['male','female'].includes(u.gender)||!['male','female'].includes(t.gender)||t.gender!==u.gender).filter(t=>!s.blocks.some(b=>(b.by===u.id&&b.target===t.id)||(b.by===t.id&&b.target===u.id))).map(t=>publicProfile(t,s)):[],peers:peers.map(p=>({id:p.id,nickname:personName(p),city:p.city,role:p.role,photo:p.role==='companion'?(p.published||p.lastPublished)?.photos.find(x=>x.status==='Approved')?.image||'':''})),connections:connections.map(visibleRecord),bookings:bookings.map(visibleRecord),orders:copy(s.orders.filter(o=>o.user===u.id)),extensions:s.extensions.filter(e=>bookings.some(b=>b.id===e.booking)).map(visibleRecord),messages:identityEligible(u)&&(u.role==='companion'||customerEligible(u))?copy(s.messages.filter(m=>threads.includes(m.connection))):[],calls:copy(s.calls.filter(c=>connections.some(x=>x.id===c.connection))),notifications:copy(s.notifications.filter(n=>n.user===u.id)),tickets:copy(s.tickets.filter(t=>t.user===u.id)),ratings:copy(s.ratings.filter(r=>bookings.some(b=>b.id===r.booking))),blocks:copy(s.blocks.filter(b=>b.by===u.id)),audit:[]};
}
export function register(s,input){must(['customer','companion'].includes(input.role),'Choose Customer or Companion.');must(validDOB(input.birthday,minimumAge(input.role)),`${input.role==='customer'?'Customers must be 25':'Companions must be 18'} or older.`);must(input.contactVerified===true,'Verify your contact first.',403);must(input.terms===true&&input.privacy===true&&(input.role!=='companion'||input.guidelines===true),'Accept the required agreements.');must(!s.users.some(u=>u.contact===input.contact&&u.status!=='deleted'),'This contact is already registered.',409);
  const name=text(input.legalName,100);must(name.length>=2,'Enter your legal name.');const city=text(input.city,60);must(city,'Choose your city.');const u={id:id(),role:input.role,status:'active',legalName:name,birthday:input.birthday,contact:input.contact,contactVerified:true,city,gender:input.gender||'prefer_not_to_say',nickname:text(input.nickname||name.split(' ')[0],30),termsAt:now(),privacyAt:now(),guidelinesAt:input.guidelines?now():null,joined:now(),identity:{status:'Not Started'},membership:null,profileStatus:'Pending Verification',draft:{nickname:text(input.nickname||name.split(' ')[0],30),bio:'',languages:[],hobbies:[],details:{},photos:[],services:[],videoEnabled:false,pausedUntil:null},published:null};s.users.push(u);record(s,u,'Registered',u.id);return u}
export function decideIdentity(s,u,result,actor={id:'identity-provider',role:'provider'}){const status=result.status;must(['Verified','Action Required','Manual Review','Rejected'].includes(status),'Invalid verification result.');if(status==='Verified'){
  must(result.authentic===true,'Provider authenticity confirmation required.');const matched=result.legalName?.trim().toLowerCase()===u.legalName.trim().toLowerCase()&&result.birthday===u.birthday;
  if(!validDOB(result.birthday,minimumAge(u.role))){u.identity={...u.identity,status:'Rejected',reason:`Age requirement not met (${minimumAge(u.role)}+).`};}
  else if(!matched)u.identity={...u.identity,status:'Action Required',reason:'Registered name or birthday does not match the verified document. Request a correction.'};
  else u.identity={...u.identity,status:'Verified',verifiedDOB:result.birthday,verifiedAt:now(),reason:'',providerRef:result.providerRef||u.identity.providerRef};
 }else u.identity={...u.identity,status,reason:text(result.reason||'Further review is needed.',300)};
 if(u.role==='companion')u.profileStatus=u.identity.status==='Verified'?'Verified—Profile Incomplete':u.identity.status==='Rejected'?'Rejected':u.identity.status==='Action Required'?'Action Required':'Pending Verification';
 notice(s,u.id,'Identity verification updated',`${u.identity.status}${u.identity.reason?`: ${u.identity.reason}`:''}`);record(s,actor,`Identity: ${u.identity.status}`,u.id,actor.role==='admin'?result.reason:u.identity.reason);return u.identity;
}
export function command(s,userId,type,data={}) { const u=getUser(s,userId);must(u.status==='active'||['ticket','account-delete','notifications-read','account-export'].includes(type),'Account access is suspended.',403);
 switch(type){
 case 'verification-start': {member(u);must(['Not Started','Action Required','Manual Review','Rejected'].includes(u.identity.status),'Verification is already underway.');u.identity={status:'Pending',providerRef:id(),submittedAt:now(),reason:''};u.profileStatus=u.role==='companion'?'Pending Verification':u.profileStatus;record(s,u,'Identity verification submitted',u.id);return copy(u.identity)}
 case 'demo-identity': {must(s.mode==='demo','Demo action unavailable.',404);member(u);must(u.identity.status==='Pending','Submit verification first.');const outcomes={verified:{status:'Verified',authentic:true,legalName:u.legalName,birthday:u.birthday},unclear:{status:'Manual Review',reason:'Fictional document needs a manual review.'},correction:{status:'Action Required',reason:'Fictional name mismatch. Please request a correction.'},rejected:{status:'Rejected',reason:'Fictional provider could not verify this document.'}};must(outcomes[data.outcome],'Choose a sample result.');return decideIdentity(s,u,outcomes[data.outcome])}
 case 'identity-correction': {member(u);must(['Action Required','Rejected','Manual Review'].includes(u.identity.status),'A correction is not required.');const legalName=text(data.legalName,100);must(legalName.length>=2&&validDOB(data.birthday,minimumAge(u.role)),'Enter valid legal details meeting the age requirement.');u.legalName=legalName;u.birthday=data.birthday;u.identity={status:'Not Started',reason:'Correction saved. Please verify again.'};u.published=null;u.profileStatus='Pending Verification';record(s,u,'Identity correction requested',u.id);return true}
 case 'profile-save': {member(u);must(u.role==='companion'&&identityEligible(u),'Verify your companion identity first.',403);const p=copy(u.draft),d=data;
  p.nickname=text(d.nickname,30);p.bio=text(d.bio,240);p.languages=(d.languages||[]).map(x=>text(x,40)).slice(0,10);p.hobbies=(d.hobbies||[]).map(x=>text(x,40)).slice(0,12);must(p.nickname&&p.bio,'Add a display name and introduction.');must(typeof d.videoEnabled==='boolean','Invalid video preference.');p.videoEnabled=d.videoEnabled;p.details={};for(const [key,value] of Object.entries(d.details||{})){must(['height','bust','waist','hips','tattoos','tattooLocation','bookingAreas','travel','smoking','drinking','availabilityNote'].includes(key),'Unknown profile detail.');p.details[key]=text(String(value),160)}
  must(Array.isArray(d.photos)&&d.photos.length<=6,'Choose up to six photos.');p.photos=d.photos.map(photo=>{const old=u.draft.photos.find(x=>x.id===photo.id&&x.image===photo.image);if(old)return copy(old);must(typeof photo.image==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(photo.image)&&photo.image.length<=450000,'Upload a JPG, PNG, or WebP image under 330 KB after resizing.');return {id:id(),image:photo.image,status:'Pending',reason:''}});
  must(Array.isArray(d.services)&&d.services.length<=3,'Choose available services.');const seen=new Set();p.services=d.services.map(rule=>{must(SERVICES.includes(rule.name)&&!seen.has(rule.name),'Choose each service once.');seen.add(rule.name);must(Array.isArray(rule.days)&&rule.days.length&&rule.days.every(x=>Number.isInteger(x)&&x>=0&&x<=6),'Choose available days.');must(/^([01]\d|2[0-3]):[0-5]\d$/.test(rule.from)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(rule.to)&&rule.from!==rule.to,'Choose a valid availability window. An earlier end time is the following day.');must(Array.isArray(rule.rates)&&rule.rates.length&&rule.rates.length<=4,'Set a duration and base price.');const hrs=new Set();const rates=rule.rates.map(r=>{must([1,2,4,8].includes(r.hours)&&!hrs.has(r.hours),'Choose unique durations (1, 2, 4 or 8 hours).');hrs.add(r.hours);price(r.basePaise);let span=(Date.parse(`2000-01-01T${rule.to}:00Z`)-Date.parse(`2000-01-01T${rule.from}:00Z`))/3600000;if(span<0)span+=24;must(r.hours<=span,'A duration must fit inside its availability window.');return {hours:r.hours,basePaise:r.basePaise}});const unavailable=(rule.unavailable||[]).map(x=>text(x,10));must(unavailable.every(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x))),'Enter unavailable dates as YYYY-MM-DD.');return {name:rule.name,days:[...new Set(rule.days)],from:rule.from,to:rule.to,area:text(rule.area||u.city,160),rates,unavailable}});
  if(d.pausedUntil){must(Number.isFinite(Date.parse(d.pausedUntil))&&Date.parse(d.pausedUntil)>Date.now(),'Choose a future pause date.');p.pausedUntil=new Date(d.pausedUntil).toISOString()}else p.pausedUntil=null;
  if(u.published)u.lastPublished=copy(u.published);if(u.lastPublished)u.lastPublished.photos=u.lastPublished.photos.filter(photo=>p.photos.some(x=>x.id===photo.id));u.draft=p;u.nickname=p.nickname;u.profileStatus='Verified—Profile Incomplete';u.published=null;notice(s,u.id,'Draft saved','Submit your changes for moderation before publication.');record(s,u,'Companion draft saved',u.id);return profileChecklist(u)}
 case 'profile-submit': {must(u.role==='companion','Companion access required.',403);must(profileChecklist(u).every(x=>x[1]),'Complete every item in the submission checklist.');u.profileStatus='Pending Admin Approval';u.submittedAt=now();u.published=null;s.users.filter(x=>x.role==='admin').forEach(a=>notice(s,a.id,'Profile ready for review',u.draft.nickname,u.id));record(s,u,'Profile submitted',u.id);return true}
 case 'profile-pause': {must(u.role==='companion'&&identityEligible(u),'Companion access required.',403);must(!data.until||Date.parse(data.until)>Date.now(),'Choose a future time.');u.draft.pausedUntil=data.until||null;record(s,u,'Availability pause changed',u.id);return true}
 case 'membership-order': {must(u.role==='customer'&&identityEligible(u),'Verify identity and age before payment.',403);must(['Payment Required','Expired','Cancelled','Payment Pending'].includes(membershipState(u)),'Membership is already active or pending.');const plan=planSnapshot(s);must(plan.enabled,'Membership checkout is unavailable.',503);const pending=s.orders.find(o=>o.user===u.id&&o.kind==='membership'&&o.status==='Pending'&&Date.parse(o.expiresAt)>Date.now());if(pending)return copy(pending);const o={id:id(),kind:'membership',user:u.id,amountPaise:plan.feePaise+plan.taxPaise,currency:'INR',plan,status:'Pending',createdAt:now(),expiresAt:new Date(Date.now()+15*60000).toISOString()};s.orders.push(o);u.membership={status:'Payment Pending',order:o.id};record(s,u,'Membership checkout created',o.id);return copy(o)}
 case 'membership-cancel': {must(u.role==='customer'&&membershipState(u)==='Active','No active membership.');u.membership.status='Cancelled';u.membership.cancelledAt=now();notice(s,u.id,'Membership cancelled','Profile access is locked. Contact support for any refund request.');record(s,u,'Membership cancelled',u.id);return true}
 case 'payment-failed': {must(s.mode==='demo','Gateway failure confirmation is required.',404);const o=s.orders.find(o=>o.id===data.id&&o.user===u.id);must(o&&o.status==='Pending','Pending order not found.',404);o.status='Failed';if(o.kind==='membership')u.membership=null;if(o.kind==='booking'){const b=s.bookings.find(b=>b.id===o.booking);b.status='Cancelled';b.reason='Payment failed.'}return true}
 case 'checkout-cancel': {const o=s.orders.find(o=>o.id===data.id&&o.user===u.id);must(o&&o.status==='Pending','Pending order not found.',404);o.status='Cancelled';if(o.kind==='membership'&&u.membership?.order===o.id)u.membership=null;if(o.kind==='booking'){const b=s.bookings.find(b=>b.id===o.booking);b.status='Cancelled';b.reason='Customer cancelled checkout.'}if(o.kind==='extension'){const x=s.extensions.find(x=>x.id===o.extension);x.status='Cancelled'}record(s,u,'Checkout cancelled',o.id);return true}
 case 'connection-create': {const t=getUser(s,data.companion);pairEligible(s,u,t);const hours=Number(data.hours),q=quote(t,data.service,hours);must(isAvailable(s,t,data.service,data.start,hours),'Choose an available future time.',409);must(!s.connections.some(c=>c.customer===u.id&&c.companion===t.id&&c.start===data.start&&['Pending','Accepted','Change Requested'].includes(c.status)),'A connection request already exists for this time.',409);const c={id:id(),customer:u.id,companion:t.id,service:data.service,start:data.start,hours,area:text(data.area||t.city,160),note:text(data.note||'',300),price:q,status:'Pending',createdAt:now(),expiresAt:new Date(Date.now()+48*3600000).toISOString(),terms:POLICY_VERSION};s.connections.push(c);notice(s,t.id,'New connection request',`${u.nickname} · ${data.service}`,c.id);record(s,u,'Connection requested',c.id);return copy(c)}
 case 'connection-revise': {const c=connection(s,u,data.id);must(c.customer===u.id&&c.status==='Change Requested','Revise a change-requested connection.',403);const t=getUser(s,c.companion);pairEligible(s,u,t);const hours=Number(data.hours),q=quote(t,data.service,hours);must(isAvailable(s,t,data.service,data.start,hours),'Choose an available future time.',409);c.history ||= [];c.history.push({service:c.service,start:c.start,hours:c.hours,price:copy(c.price),reason:c.reason,at:now()});Object.assign(c,{service:data.service,start:data.start,hours,price:q,area:text(data.area||t.city,160),note:text(data.note||'',300),status:'Pending',reason:'',expiresAt:new Date(Date.now()+48*3600000).toISOString()});notice(s,t.id,'Connection request revised',u.nickname,c.id);record(s,u,'Connection revised',c.id);return copy(c)}
 case 'connection-respond': {const c=connection(s,u,data.id);must(c.companion===u.id&&['Pending','Change Requested'].includes(c.status),'Only the companion can respond to a pending request.',403);must(['Accepted','Declined','Change Requested'].includes(data.status),'Choose a response.');if(data.status==='Accepted'){pairEligible(s,getUser(s,c.customer),u);must(isAvailable(s,u,c.service,c.start,c.hours),'That time is no longer available.',409)}if(data.status!=='Accepted')must(text(data.reason||'',300),'Give a reason or requested change.');c.status=data.status;c.reason=text(data.reason||'',300);c.respondedAt=now();notice(s,c.customer,`Connection ${c.status.toLowerCase()}`,c.reason||'Chat is now open. Arrange your booking.',c.id);record(s,u,`Connection: ${c.status}`,c.id,c.reason);return true}
 case 'connection-cancel': {const c=connection(s,u,data.id);must(['Pending','Change Requested','Accepted'].includes(c.status),'Request is already closed.');c.status='Cancelled';notice(s,c.customer===u.id?c.companion:c.customer,'Connection cancelled','The conversation is closed.',c.id);return true}
 case 'booking-create': {const c=connection(s,u,data.connection);must(c.customer===u.id&&c.status==='Accepted','An accepted connection is required.',403);const t=getUser(s,c.companion);pairEligible(s,u,t);must(isAvailable(s,t,c.service,c.start,c.hours),'This time is no longer available.',409);must(!s.bookings.some(b=>b.connection===c.id&&!['Cancelled','Completed'].includes(b.status)),'A booking already exists for this request.',409);const b={id:id(),reference:`HL-${id().slice(0,8).toUpperCase()}`,connection:c.id,customer:u.id,companion:t.id,service:c.service,start:c.start,hours:c.hours,price:copy(c.price),venue:text(data.venue,180),status:'Awaiting Response',paymentStatus:'Unpaid',checkIns:[],createdAt:now()};must(b.venue,'Add a venue.');s.bookings.push(b);notice(s,t.id,'Booking request',`${u.nickname} · ${b.service} · ${b.venue}`,b.id);record(s,u,'Booking submitted',b.id);return copy(b)}
 case 'booking-respond': {const b=booking(s,u,data.id);must(b.companion===u.id&&b.status==='Awaiting Response','Only the companion can respond to this booking.',403);must(['accept','decline'].includes(data.decision),'Choose accept or decline.');if(data.decision==='accept'){pairEligible(s,getUser(s,b.customer),u);must(isAvailable(s,u,b.service,b.start,b.hours,b.id),'This slot is no longer available.',409);b.status='Payment Pending';b.acceptedAt=now();b.holdUntil=new Date(Date.now()+15*60000).toISOString()}else{must(text(data.reason||'',300),'Give a reason.');b.status='Cancelled';b.reason=text(data.reason,300)}notice(s,b.customer,`Booking ${data.decision==='accept'?'accepted':'declined'}`,data.decision==='accept'?'Review the final amount and pay within 15 minutes to confirm.':b.reason,b.id);record(s,u,`Booking ${data.decision}`,b.id,b.reason);return true}
 case 'booking-order': {const b=booking(s,u,data.id);must(b.customer===u.id&&customerEligible(u),'Active membership required.',403);must(b.status==='Payment Pending'&&Date.parse(b.holdUntil)>Date.now()&&Date.parse(b.start)>Date.now(),'The payment hold expired. Request a new booking.',409);must(companionVisible(getUser(s,b.companion)),'Companion is unavailable.',409);let o=s.orders.find(x=>x.booking===b.id&&x.kind==='booking'&&x.status==='Pending');if(o)return copy(o);o={id:id(),kind:'booking',user:u.id,booking:b.id,amountPaise:b.price.customerPaise+b.price.taxPaise+b.price.feePaise,currency:'INR',status:'Pending',createdAt:now(),expiresAt:b.holdUntil};s.orders.push(o);return copy(o)}
 case 'booking-checkin': {const b=booking(s,u,data.id);must(['Confirmed','In Progress'].includes(b.status),'Confirmed payment is required.',403);must(identityEligible(u)&&(u.role==='companion'||customerEligible(u)),'Account access is restricted.',403);must(Date.now()>=Date.parse(b.start)-2*3600000&&Date.now()<Date.parse(b.start)+(b.hours+2)*3600000,'Check-in opens two hours before the booking.');if(!b.checkIns.some(c=>c.user===u.id))b.checkIns.push({user:u.id,at:now(),venueConfirmed:true});if(b.checkIns.length===2){b.status='In Progress';b.actualStart=now()}record(s,u,'Arrival confirmed',b.id);return true}
 case 'booking-complete': {const b=booking(s,u,data.id);must(['Confirmed','In Progress'].includes(b.status),'Booking is not active.');b.status='Completed';b.endedAt=now();notice(s,b.customer,'Booking completed','Share feedback or contact support.',b.id);notice(s,b.companion,'Booking completed','The booking record is available. Payouts require an approved model.',b.id);record(s,u,'Booking completed',b.id);return true}
 case 'booking-dispute': {const b=booking(s,u,data.id);must(b.status!=='Disputed','Booking is already disputed.');must(text(data.reason||'',300),'Describe the dispute.');b.status='Disputed';b.disputedAt=now();b.disputeReason=text(data.reason,300);const t={id:id(),reference:`SUP-${id().slice(0,8).toUpperCase()}`,user:u.id,category:'Booking dispute',subject:`Dispute: ${b.reference}`,referenceId:b.id,status:'Open',messages:[{from:u.id,body:b.disputeReason,at:now()}],createdAt:now()};s.tickets.push(t);notice(s,b.customer,'Booking disputed','Support will review the record.',b.id);notice(s,b.companion,'Booking disputed','Support will review the record.',b.id);record(s,u,'Booking disputed',b.id,b.disputeReason);return t}
 case 'booking-cancel': {const b=booking(s,u,data.id);must(!['Cancelled','Completed','Disputed'].includes(b.status),'Booking is already closed.');must(text(data.reason||'',300),'Give a reason.');b.status='Cancelled';b.reason=text(data.reason,300);notice(s,b.customer===u.id?b.companion:b.customer,'Booking cancelled',b.reason,b.id);record(s,u,'Booking cancelled',b.id,b.reason);return true}
 case 'extension-create': {const b=booking(s,u,data.id);must(b.customer===u.id&&customerEligible(u)&&['Confirmed','In Progress'].includes(b.status),'An active booking and membership are required.',403);must([1,2,4].includes(data.hours),'Choose one, two, or four extra hours.');must(!s.extensions.some(e=>e.booking===b.id&&['Pending','Payment Pending'].includes(e.status)),'An extension is already pending.',409);const base=Math.ceil((b.price.basePaise/b.price.hours*data.hours)/2)*2;const x={id:id(),booking:b.id,hours:data.hours,basePaise:base,customerPaise:price(base),status:'Pending',createdAt:now()};s.extensions.push(x);notice(s,b.companion,'Extension requested',`${data.hours} additional hours`,x.id);return copy(x)}
 case 'extension-respond': {const x=s.extensions.find(x=>x.id===data.id);must(x,'Extension not found.',404);const b=booking(s,u,x.booking);must(b.companion===u.id&&x.status==='Pending'&&['Confirmed','In Progress'].includes(b.status),'Companion response required.',403);must(['accept','decline'].includes(data.decision),'Choose accept or decline.');if(data.decision==='accept'){must(!conflicts(s,u.id,b.start,b.hours+x.hours,b.id),'Extension conflicts with another booking.',409);x.status='Payment Pending';x.holdUntil=new Date(Date.now()+15*60000).toISOString()}else x.status='Declined';notice(s,b.customer,`Extension ${data.decision==='accept'?'accepted':'declined'}`,data.decision==='accept'?'Review and pay the additional amount to extend the booking.':'Your booking end time is unchanged.',x.id);return true}
 case 'extension-order': {const x=s.extensions.find(x=>x.id===data.id);must(x,'Extension not found.',404);const b=booking(s,u,x.booking);must(b.customer===u.id&&customerEligible(u)&&x.status==='Payment Pending'&&Date.parse(x.holdUntil)>Date.now()&&['Confirmed','In Progress'].includes(b.status),'Extension checkout unavailable.',403);let o=s.orders.find(o=>o.extension===x.id&&o.status==='Pending');if(o)return copy(o);o={id:id(),kind:'extension',user:u.id,booking:b.id,extension:x.id,amountPaise:x.customerPaise,currency:'INR',status:'Pending',expiresAt:x.holdUntil,createdAt:now()};s.orders.push(o);return copy(o)}
 case 'message': {const c=connection(s,u,data.id);must(c.status==='Accepted','Accept the connection before messaging.',403);interactionEligible(s,c);const body=text(data.body,2000);must(body,'Write a message.');const m={id:id(),connection:c.id,from:u.id,body,at:now(),readBy:[u.id]};s.messages.push(m);notice(s,c.customer===u.id?c.companion:c.customer,'New message',`${personName(u)} sent a message.`,c.id);return m}
 case 'messages-read': {const c=connection(s,u,data.id);s.messages.filter(m=>m.connection===c.id).forEach(m=>{if(!m.readBy.includes(u.id))m.readBy.push(u.id)});return true}
 case 'call-request': {const c=connection(s,u,data.id);must(c.status==='Accepted','Accept the connection first.',403);interactionEligible(s,c);if(data.kind!=='audio')must(getUser(s,c.companion).published.videoEnabled,'Video introductions are disabled.');must(!s.calls.some(x=>x.connection===c.id&&['Ringing','Accepted'].includes(x.status)),'A call is already active.',409);const call={id:id(),kind:data.kind==='audio'?'audio':'video',connection:c.id,from:u.id,to:c.customer===u.id?c.companion:c.customer,status:'Ringing',at:now(),signals:[]};s.calls.push(call);notice(s,call.to,call.kind==='audio'?'Voice call request':'Video introduction request',`${personName(u)} would like a video introduction.`,call.id);return {id:call.id}}
 case 'call-respond': {const call=s.calls.find(x=>x.id===data.id);must(call&&call.to===u.id&&call.status==='Ringing','Incoming call not found.',404);must(['Accepted','Declined'].includes(data.status),'Choose a call response.');const c=connection(s,u,call.connection);interactionEligible(s,c);call.status=data.status;if(call.status==='Accepted')call.acceptedAt=now();return true}
 case 'call-end': {const call=s.calls.find(x=>x.id===data.id);must(call&&[call.from,call.to].includes(u.id),'Call not found.',404);call.status='Ended';call.endedAt=now();return true}
 case 'call-signal': {const call=s.calls.find(x=>x.id===data.id);must(call&&call.status==='Accepted'&&[call.from,call.to].includes(u.id),'Accepted call required.',403);const c=connection(s,u,call.connection);interactionEligible(s,c);must(['offer','answer','candidate'].includes(data.signal?.type)&&JSON.stringify(data.signal).length<20000&&call.signals.length<200,'Invalid call signal.');call.signals.push({id:id(),from:u.id,at:now(),...data.signal});return true}
 case 'rating': {const b=booking(s,u,data.id);must(b.customer===u.id&&b.status==='Completed','Rate a completed booking.',403);must(Number.isInteger(data.value)&&data.value>=1&&data.value<=5,'Choose 1–5 stars.');must(!s.ratings.some(r=>r.booking===b.id&&r.from===u.id),'You already rated this booking.',409);s.ratings.push({id:id(),booking:b.id,from:u.id,about:b.companion,value:data.value,at:now()});return true}
 case 'block': {member(u);const target=getUser(s,data.target);must(target.id!==u.id&&target.role!=='admin','Invalid account.');if(!s.blocks.some(b=>b.by===u.id&&b.target===target.id))s.blocks.push({id:id(),by:u.id,target:target.id,at:now()});s.connections.filter(c=>[c.customer,c.companion].includes(u.id)&&[c.customer,c.companion].includes(target.id)).forEach(c=>c.status='Cancelled');s.calls.filter(c=>[c.from,c.to].includes(u.id)&&[c.from,c.to].includes(target.id)).forEach(c=>c.status='Ended');record(s,u,'Account blocked',target.id);return true}
 case 'unblock': {s.blocks=s.blocks.filter(b=>!(b.by===u.id&&b.target===data.target));return true}
 case 'ticket': {const subject=text(data.subject,120),body=text(data.body,2000);must(subject&&body,'Add a subject and description.');const t={id:id(),reference:`SUP-${id().slice(0,8).toUpperCase()}`,user:u.id,category:data.category||'Support',subject,referenceId:text(data.reference||'',100),status:'Open',messages:[{from:u.id,body,at:now()}],createdAt:now()};s.tickets.push(t);record(s,u,'Support ticket opened',t.id);return t}
 case 'ticket-reply': {const t=s.tickets.find(t=>t.id===data.id);must(t&&(t.user===u.id||u.role==='admin'),'Ticket not found.',404);const body=text(data.body,2000);must(body,'Write a reply.');t.messages.push({from:u.id,body,at:now()});if(u.role==='admin'&&['Open','In Review','Resolved'].includes(data.status))t.status=data.status;notice(s,t.user,'Support update',t.reference,t.id);record(s,u,'Support ticket updated',t.id);return true}
 case 'notifications-read': {s.notifications.filter(n=>n.user===u.id).forEach(n=>n.read=true);return true}
 case 'account-save': {member(u);u.nickname=text(data.nickname,30);must(u.nickname,'Enter a nickname.');u.notificationsEnabled=data.notificationsEnabled!==false;record(s,u,'Account preferences saved',u.id);return true}
 case 'account-deactivate': {member(u);must(!s.bookings.some(b=>[b.customer,b.companion].includes(u.id)&&['Confirmed','In Progress'].includes(b.status)),'Cancel or complete active bookings before deactivation.');u.status='deactivated';u.published=null;record(s,u,'Account deactivated',u.id);return true}
 case 'account-delete': {must(u.role!=='admin','Administrators cannot use member deletion.');must(!s.bookings.some(b=>[b.customer,b.companion].includes(u.id)&&['Confirmed','In Progress'].includes(b.status)),'Cancel or complete active bookings before deletion.');record(s,u,'Account deleted',u.id);u.status='deleted';u.legalName='Deleted account';u.nickname='Deleted account';u.contact='';u.birthday='';u.identity={status:'Not Started'};u.published=null;u.lastPublished=null;u.draft={};s.messages=s.messages.filter(m=>m.from!==u.id);s.sessionsRevoked ||= [];s.sessionsRevoked.push(u.id);return true}
 case 'account-export': return view(s,u.id);
 case 'admin-identity': {admin(u);const t=getUser(s,data.id);must(t.identity.status==='Manual Review','Manual review required.');must(text(data.reason||'',300),'Record a reason.');must(['Verified','Action Required','Rejected'].includes(data.status),'Choose a review decision.');return decideIdentity(s,t,{status:data.status,authentic:data.authentic===true,legalName:data.legalName,birthday:data.birthday,reason:data.reason},u)}
 case 'admin-photo': {admin(u);const t=getUser(s,data.id),photo=t.draft.photos.find(x=>x.id===data.photo);must(photo&&['Approved','Rejected'].includes(data.status),'Choose a photo and decision.');if(data.status==='Rejected')must(text(data.reason||'',300),'Give a rejection reason.');photo.status=data.status;photo.reason=text(data.reason||'',300);t.published=null;if(t.profileStatus==='Approved')t.profileStatus='Changes Required';record(s,u,`Photo ${data.status.toLowerCase()}`,t.id,photo.reason);notice(s,t.id,'Photo review updated',photo.reason||'A photo was approved.');return true}
 case 'admin-profile': {admin(u);const t=getUser(s,data.id);must(t.role==='companion'&&['Pending Admin Approval','Changes Required','Rejected'].includes(t.profileStatus),'Profile is not in the review queue.');must(['Approved','Changes Required','Rejected'].includes(data.status),'Choose a profile decision.');if(data.status==='Approved'){must(profileChecklist(t).every(x=>x[1])&&t.draft.photos.some(x=>x.status==='Approved')&&t.draft.photos.every(x=>x.status!=='Pending'),'Complete identity and individual photo reviews first.');t.published=copy(t.draft);t.lastPublished=copy(t.published);t.published.photos=t.draft.photos.filter(x=>x.status==='Approved');t.approvedAt=now()}else{must(text(data.reason||'',300),'Give a correction or rejection reason.');t.published=null}t.profileStatus=data.status;t.reviewReason=text(data.reason||'',300);notice(s,t.id,`Profile ${data.status.toLowerCase()}`,t.reviewReason||'Your profile is now visible to eligible customers.');record(s,u,`Profile ${data.status.toLowerCase()}`,t.id,t.reviewReason);return true}
 case 'admin-account': {admin(u);const t=getUser(s,data.id);must(t.role!=='admin','Member accounts only.');must(['suspended','active','deleted'].includes(data.status)&&text(data.reason||'',300),'Select a decision and provide a reason.');if(data.status==='active')must(['suspended','deactivated'].includes(t.status),'Only suspended or deactivated accounts can be restored.');if(data.status==='deleted')must(!s.bookings.some(b=>[b.customer,b.companion].includes(t.id)&&['Confirmed','In Progress'].includes(b.status)),'Cancel active bookings before deletion.');t.status=data.status;if(data.status==='deleted'){t.legalName='Deleted account';t.nickname='Deleted account';t.contact='';t.birthday='';t.draft={};t.published=null;t.lastPublished=null;t.identity={status:'Not Started'};s.messages=s.messages.filter(m=>m.from!==t.id)}s.sessionsRevoked ||= [];s.sessionsRevoked.push(t.id);notice(s,t.id,`Account ${data.status}`,data.reason);record(s,u,`Account ${data.status}`,t.id,data.reason);return true}
 case 'admin-refund': {admin(u);const o=s.orders.find(o=>o.id===data.id);must(o&&['Paid','Refunded'].includes(o.status),'Confirmed payment required.',404);const reason=text(data.reason||'',300);must(reason,'Record the refund reason.');const pending=(o.refunds||[]).find(r=>r.status==='Requested');if(pending)return copy(pending);const remaining=o.amountPaise-(o.refunds||[]).filter(r=>r.status==='Confirmed').reduce((n,r)=>n+r.amountPaise,0);must(Number.isSafeInteger(data.amountPaise)&&data.amountPaise>0&&data.amountPaise<=remaining,'Refund must not exceed the unrefunded amount.');const refund={id:id(),order:o.id,user:o.user,amountPaise:data.amountPaise,currency:o.currency,status:'Requested',reason,requestedAt:now()};o.refunds ||= [];o.refunds.push(refund);record(s,u,'Refund requested',o.id,reason);return copy(refund)}
 case 'admin-plan': {admin(u);must(Number.isSafeInteger(data.feePaise)&&data.feePaise>=100&&data.feePaise<=10000000&&Number.isSafeInteger(data.taxPaise)&&data.taxPaise>=0&&data.taxPaise<=10000000&&Number.isInteger(data.days)&&data.days>=1&&data.days<=365,'Enter valid pricing and validity.');must(text(data.cancellation,1000)&&text(data.renewal,1000),'Disclose cancellation and renewal terms.');s.settings.membership={...s.settings.membership,name:text(data.name,80),feePaise:data.feePaise,taxPaise:data.taxPaise,days:data.days,cancellation:text(data.cancellation,1000),renewal:text(data.renewal,1000),enabled:!!data.enabled,version:id()};record(s,u,'Membership plan updated',s.settings.membership.version);return true}
 default: throw new RuleError('Unknown action.',404);
 }
}
export function settle(s,orderId,event){const o=s.orders.find(x=>x.id===orderId);must(o,'Order not found.',404);must(event.currency===o.currency&&event.amountPaise===o.amountPaise&&event.status==='paid','Gateway payment does not match the order.',400);if(o.status==='Paid')return {duplicate:true};must(['Pending','Expired','Cancelled','Failed'].includes(o.status),'Order is closed.',409);const u=s.users.find(u=>u.id===o.user);must(u,'Account not found.',404);const timely=o.status==='Pending'&&Date.parse(o.expiresAt)>Date.now();
 if(o.kind==='membership'){if(!identityEligible(u)||!timely){o.status='Review Required';o.providerRef=event.providerRef;notice(s,u.id,'Payment needs review','Eligibility or checkout expiry changed. Contact support for reconciliation.',o.id);return {review:true}}u.membership={status:'Active',startsAt:now(),expiresAt:new Date(Date.now()+o.plan.days*86400000).toISOString(),plan:copy(o.plan),order:o.id,autoRenew:false};notice(s,u.id,'Membership active',`Access valid until ${u.membership.expiresAt.slice(0,10)}.`,o.id)}
 if(o.kind==='booking'){const b=s.bookings.find(x=>x.id===o.booking);if(!timely||!customerEligible(u)||!companionVisible(getUser(s,b.companion))||b.status!=='Payment Pending'||Date.parse(b.start)<=Date.now()||conflicts(s,b.companion,b.start,b.hours,b.id)){o.status='Review Required';o.providerRef=event.providerRef;notice(s,u.id,'Payment needs review','The booking could not be confirmed. Contact support for reconciliation.',o.id);return {review:true}}b.status='Confirmed';b.paymentStatus='Paid';b.confirmedAt=now();b.paymentRef=event.providerRef;notice(s,b.customer,'Booking confirmed',b.reference,b.id);notice(s,b.companion,'Booking confirmed',b.reference,b.id)}
 if(o.kind==='extension'){const x=s.extensions.find(x=>x.id===o.extension),b=s.bookings.find(x=>x.id===o.booking);if(!timely||!customerEligible(u)||!companionVisible(getUser(s,b.companion))||x.status!=='Payment Pending'||!['Confirmed','In Progress'].includes(b.status)||conflicts(s,b.companion,b.start,b.hours+x.hours,b.id)){o.status='Review Required';o.providerRef=event.providerRef;notice(s,u.id,'Extension payment needs review','Contact support for reconciliation.',o.id);return {review:true}}x.status='Confirmed';b.hours+=x.hours;b.extensions ||= [];b.extensions.push({id:x.id,hours:x.hours,customerPaise:x.customerPaise,paymentRef:event.providerRef,at:now()});notice(s,b.companion,'Booking extended',`${x.hours} extra hours confirmed.`,b.id)}
 o.status='Paid';o.paidAt=now();o.providerRef=event.providerRef;record(s,{id:'payment-gateway'},'Gateway payment confirmed',o.id);return {paid:true}
}
export function maintain(s){for(const u of s.users){if(u.role==='customer'&&u.membership?.status==='Active'){const remaining=Date.parse(u.membership.expiresAt)-Date.now();if(remaining<=0){u.membership.status='Expired';notice(s,u.id,'Membership expired','Renew to restore profile access.')}else if(remaining<3*86400000&&!u.membership.reminded){u.membership.reminded=true;notice(s,u.id,'Membership renewal reminder','Your membership expires within three days. Renewal is manual.')}}}
 s.connections.forEach(c=>{if(['Pending','Change Requested'].includes(c.status)&&Date.parse(c.expiresAt)<=Date.now()){c.status='Expired';notice(s,c.customer,'Connection expired','Send a new request if you would still like to connect.',c.id)}});
 s.bookings.forEach(b=>{if(b.status==='Payment Pending'&&Date.parse(b.holdUntil)<=Date.now()){b.status='Cancelled';b.reason='Payment hold expired.';notice(s,b.customer,'Booking hold expired','Request a new booking.',b.id)}});
 s.orders.forEach(o=>{if(o.status==='Pending'&&Date.parse(o.expiresAt)<=Date.now()){o.status='Expired';if(o.kind==='membership'){const u=s.users.find(u=>u.id===o.user);if(u?.membership?.order===o.id)u.membership=null}}});
 s.extensions.forEach(x=>{if(x.status==='Payment Pending'&&Date.parse(x.holdUntil)<=Date.now())x.status='Expired'});
 s.calls.forEach(c=>{const connection=s.connections.find(x=>x.id===c.connection),customer=s.users.find(u=>u.id===connection?.customer),companion=s.users.find(u=>u.id===connection?.companion);if(['Ringing','Accepted'].includes(c.status)&&(!customerEligible(customer)||(!identityEligible(companion)||['Rejected','Suspended'].includes(companion.profileStatus))||connection?.status!=='Accepted')){c.status='Ended';c.endedAt=now();c.signals=[]}if(c.status==='Ringing'&&Date.parse(c.at)+60000<=Date.now())c.status='Missed';if(c.status==='Accepted'&&Date.parse(c.acceptedAt)+30*60000<=Date.now()){c.status='Ended';c.endedAt=now()}});
}
export function createSeed(mode='demo'){const s={schema:2,mode,settings:{membership:{name:'Private Circle',feePaise:159900,taxPaise:0,days:30,enabled:mode==='demo',features:['Approved companion profiles','Connection requests','Chat after acceptance','Booking requests'],renewal:'30 days. Manual renewal; no recurring charge.',cancellation:'Demo policy: access stops on cancellation. Refunds are reviewed through support. Live terms must be approved before launch.',version:'demo-plan-v1'},payoutModelApproved:false},users:[],connections:[],bookings:[],extensions:[],orders:[],messages:[],calls:[],ratings:[],notifications:[],tickets:[],blocks:[],audit:[]};if(mode!=='demo')return s;
 const portraits=['photo-1534528741775-53994a69daeb','photo-1524504388940-b1c1722653e1','photo-1517841905240-472988babdf9'];
 for(const [i,name] of ['Aanya Rao','Meera Shah','Naina Kapoor'].entries()){const u=register(s,{role:'companion',legalName:name,nickname:name.split(' ')[0],birthday:['1997-04-22','1996-10-10','1998-03-02'][i],city:i===2?'Mumbai':'Bengaluru',gender:'female',contact:`${name.split(' ')[0].toLowerCase()}@demo.highlife`,contactVerified:true,terms:true,privacy:true,guidelines:true});u.id=['aanya','meera','naina'][i];u.identity={status:'Verified',verifiedDOB:u.birthday,verifiedAt:now(),providerRef:`fictional-${i}`};u.draft={nickname:u.nickname,bio:['Coffee loyalist, gallery wanderer and a believer in unhurried conversation.','A curious spirit with a soft spot for art, new neighbourhoods and a great dessert menu.','Film nights, sea breeze, and discovering restaurants before everyone else does.'][i],hobbies:[['Coffee','Art','Books'],['Travel','Galleries','Music'],['Movies','Music','Food']][i],languages:['English','Hindi'],details:{height:'165 cm',bust:'34 in',waist:'30 in',hips:'40 in',tattoos:'No',bookingAreas:u.city,travel:'Yes',smoking:'No',drinking:'Occasionally',availabilityNote:'Weekday evenings and weekends'},photos:[{id:`photo-${i}`,image:`https://images.unsplash.com/${portraits[i]}?auto=format&fit=crop&w=900&q=85`,status:'Approved',reason:''}],videoEnabled:true,pausedUntil:null,services:SERVICES.map((name,i)=>({name,days:[0,1,2,3,4,5,6],from:'09:00',to:'23:00',area:u.city,rates:name==='Social'?[{hours:2,basePaise:180000},{hours:4,basePaise:300000}]:name==='Mini Date'?[{hours:1,basePaise:80000},{hours:2,basePaise:140000}]:[{hours:4,basePaise:350000},{hours:8,basePaise:600000}],unavailable:[]}))};u.profileStatus='Approved';u.published=copy(u.draft)}
 for(const [i,name] of ['Arjun Mehta','Rohan Sen','Karan Malhotra','Dev New'].entries()){const u=register(s,{role:'customer',legalName:name,birthday:'1995-06-14',city:'Bengaluru',gender:'male',contact:`${name.split(' ')[0].toLowerCase()}@demo.highlife`,contactVerified:true,terms:true,privacy:true});u.id=['arjun','rohan','karan','new-customer'][i];if(i!==3)u.identity={status:'Verified',verifiedDOB:u.birthday,verifiedAt:now()};if(i<2)u.membership={status:'Active',startsAt:now(),expiresAt:new Date(Date.now()+30*86400000).toISOString(),plan:copy(s.settings.membership),autoRenew:false}}
 const isha=register(s,{role:'companion',legalName:'Isha Verma',birthday:'1999-07-08',city:'Bengaluru',gender:'female',contact:'isha@demo.highlife',contactVerified:true,terms:true,privacy:true,guidelines:true});isha.id='isha';isha.identity={status:'Manual Review',providerRef:'fictional-review',reason:'Fictional document needs a manual review.'};
 for(const [i,name] of ['Aditi Sharma','Vikram Rao','Sana Khan','Dev Patel'].entries())s.users.push({id:`admin${i+1}`,role:'admin',status:'active',legalName:name,nickname:name.split(' ')[0],contact:`admin${i+1}@demo.highlife`,city:'Bengaluru',scope:['Owner','Review','Safety','Operations'][i],identity:{status:'Verified'},draft:{}});
 s.audit=[];return s;
}

export function settleRefund(s,orderId,event){const o=s.orders.find(o=>o.id===orderId),refund=o?.refunds?.find(r=>r.id===event.refundReference);must(o&&refund,'Refund request not found.',404);must(event.amountPaise===refund.amountPaise&&event.currency===o.currency&&event.status==='refunded','Gateway refund does not match the request.');if(refund.status==='Confirmed')return {duplicate:true};refund.status='Confirmed';refund.providerRef=event.providerRef;refund.confirmedAt=now();const sum=o.refunds.filter(r=>r.status==='Confirmed').reduce((n,r)=>n+r.amountPaise,0);if(sum===o.amountPaise){o.status='Refunded';if(o.kind==='membership'){const u=s.users.find(u=>u.id===o.user);if(u.membership?.order===o.id)u.membership.status='Cancelled'}if(o.kind==='booking'){const b=s.bookings.find(b=>b.id===o.booking);b.paymentStatus='Refunded';if(['Payment Pending','Confirmed'].includes(b.status))b.status='Cancelled'}}notice(s,o.user,'Refund confirmed',`${refund.amountPaise/100} INR refunded by the gateway.`,o.id);record(s,{id:'payment-gateway'},'Gateway refund confirmed',o.id,refund.reason);return {refunded:true}}
export function gatewayFailure(s,orderId,event){const o=s.orders.find(o=>o.id===orderId);must(o&&event.amountPaise===o.amountPaise&&event.currency===o.currency&&event.status==='failed','Gateway failure does not match the order.');if(o.status==='Paid'||o.status==='Refunded')return {ignored:true};if(o.status==='Failed')return {duplicate:true};o.status='Failed';o.providerRef=event.providerRef;const u=s.users.find(u=>u.id===o.user);if(o.kind==='membership'&&u.membership?.order===o.id)u.membership=null;if(o.kind==='booking'){const b=s.bookings.find(b=>b.id===o.booking);if(b.status==='Payment Pending'){b.status='Cancelled';b.reason='Payment failed at the gateway.'}}if(o.kind==='extension'){const x=s.extensions.find(x=>x.id===o.extension);x.status='Declined'}notice(s,o.user,'Payment failed','The gateway did not confirm payment. Review your status before retrying.',o.id);record(s,{id:'payment-gateway'},'Gateway payment failed',o.id);return {failed:true}}
